# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/FPGA_projects/TOF_4Ports/TOF_4Ports.cache/wt [current_project]
set_property parent.project_path E:/FPGA_projects/TOF_4Ports/TOF_4Ports.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.0 [current_project]
set_property ip_output_repo e:/FPGA_projects/TOF_4Ports/TOF_4Ports.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib E:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
add_files E:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_dist_mem_gen_0_0/design_1_dist_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_dist_mem_gen_0_1/design_1_dist_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_dist_mem_gen_0_2/design_1_dist_mem_gen_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_dist_mem_gen_0_3/design_1_dist_mem_gen_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_2_2/design_1_axi_gpio_2_2_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_2_2/design_1_axi_gpio_2_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_2_2/design_1_axi_gpio_2_2.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_4_0/design_1_axi_gpio_4_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_4_0/design_1_axi_gpio_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_4_0/design_1_axi_gpio_4_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_2/design_1_microblaze_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_2/design_1_dlmb_v10_2.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_2/design_1_dlmb_v10_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_2/design_1_ilmb_v10_2.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_2/design_1_ilmb_v10_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_2/design_1_dlmb_bram_if_cntlr_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_2/design_1_ilmb_bram_if_cntlr_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_2/design_1_lmb_bram_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_1/design_1_microblaze_0_axi_intc_1.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_1/design_1_microblaze_0_axi_intc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_axi_intc_1/design_1_microblaze_0_axi_intc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_2/design_1_mdm_1_2.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_2/design_1_mdm_1_2_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_80M_2/design_1_rst_mig_7series_0_80M_2_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_80M_2/design_1_rst_mig_7series_0_80M_2.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_80M_2/design_1_rst_mig_7series_0_80M_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernetlite_0_1/design_1_axi_ethernetlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernetlite_0_1/design_1_axi_ethernetlite_0_1.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernetlite_0_1/design_1_axi_ethernetlite_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernetlite_0_1/design_1_axi_ethernetlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_1/design_1_axi_timer_0_1.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_timer_0_1/design_1_axi_timer_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_1/bd_6f02_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_1/bd_6f02_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_2/bd_6f02_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_3/bd_6f02_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_4/bd_6f02_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_5/bd_6f02_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_6/bd_6f02_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_10/bd_6f02_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_11/bd_6f02_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_12/bd_6f02_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_13/bd_6f02_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_14/bd_6f02_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_15/bd_6f02_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_19/bd_6f02_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_20/bd_6f02_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_21/bd_6f02_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_22/bd_6f02_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_23/bd_6f02_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_24/bd_6f02_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_25/bd_6f02_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_26/bd_6f02_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_27/bd_6f02_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_eventCounter0_1/design_1_axi_gpio_eventCounter0_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_eventCounter0_1/design_1_axi_gpio_eventCounter0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_eventCounter0_1/design_1_axi_gpio_eventCounter0_1.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_eventCounter2_0/design_1_axi_gpio_eventCounter2_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_eventCounter2_0/design_1_axi_gpio_eventCounter2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_eventCounter2_0/design_1_axi_gpio_eventCounter2_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_eventCounter0_0/design_1_axi_gpio_eventCounter0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_eventCounter0_0/design_1_axi_gpio_eventCounter0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_eventCounter0_0/design_1_axi_gpio_eventCounter0_0.xdc]
set_property used_in_implementation false [get_files -all E:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/constrs_1/imports/digilent-xdc-master/Arty-A7-35-Master.xdc
set_property used_in_implementation false [get_files E:/FPGA_projects/TOF_4Ports/TOF_4Ports.srcs/constrs_1/imports/digilent-xdc-master/Arty-A7-35-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
